### ISSUE TITLE
Getting SSL Certificate ERROR 

### ISSUE THREAD

**Issue by tanvimadan** [goldbergjeffrey/QlikSenseTicket.java#2]
Hi,

Replicated all steps as defined here please suggest solution as i am getting SSL Handshake Error.

**Comment by goldbergjeffrey** [comment]
Please see **#1** which discusses potential issues you may have with the java keystore.

**Comment by goldbergjeffrey** [comment]
@tanvimadan based on your response earlier on #1, I'm closing this issue.
